# Traefik Global Configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Core configuration
core:
  defaultRuleSyntax: v2

# Configure the entry points
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# API and dashboard configuration
api:
  dashboard: true
  insecure: false

# Configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: traefik-public
  file:
    directory: /config
    watch: true

# Let's Encrypt configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: info@lexicon.id
      storage: acme.json
      httpChallenge:
        entryPoint: web

# Access logs
accessLog:
  filePath: /var/log/traefik/access.log

# Log information
log:
  level: INFO
