# Traefik Global Configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Configure the entry points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# API and dashboard configuration
api:
  dashboard: true
  insecure: false

# Configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: ${DOCKER_NETWORK}
  file:
    directory: /config
    watch: true

# Let's Encrypt configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: acme.json
      httpChallenge:
        entryPoint: web

# Access logs
accessLog:
  filePath: /var/log/traefik/access.log

# Log information
log:
  level: ${TRAEFIK_LOG_LEVEL}
