http:
  middlewares:
    cloudflare-flexible:
      chain:
        middlewares:
          - no-ssl@file

    # This middleware adds X-Forwarded-Proto header if missing
    add-proto:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
