http:
  middlewares:
    secure-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    compress:
      compress: {}

    cors:
      headers:
        allowCredentials: true
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOrigins:
          - "https://lexicon.id"
          - "https://*.lexicon.id"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true

    rate-limit:
      rateLimit:
        average: 100
        burst: 50
