http:
  middlewares:
    secure-headers:
      headers:
        frameDeny: false
        sslRedirect: false
        browserXssFilter: false
        contentTypeNosniff: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceStsHeader: true
        contentSecurityPolicy: "frame-ancestors 'self'"
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=()"
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    compress:
      compress: {}

    cors:
      cors:
        allowCredentials: true
        allowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowOrigins:
          - "https://lexicon.id"
          - "https://*.lexicon.id"
        maxAge: 100
        addVaryHeader: true

    rate-limit:
      rateLimit:
        average: 100
        burst: 50
