http:
  middlewares:
    secure-headers:
      headers:
        contentTypeNosniff: true
        stsSeconds: 0
        stsIncludeSubdomains: false
        stsPreload: false
        forceStsHeader: false
        contentSecurityPolicy: "frame-ancestors 'self'"
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=()"
        customFrameOptionsValue: SAMEORIGIN
