http:
  middlewares:
    secure-headers:
      headers:
        contentTypeNosniff: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceStsHeader: true
        contentSecurityPolicy: "frame-ancestors 'self'"
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=()"
        customFrameOptionsValue: SAMEORIGIN
