
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"     # HTTP
      - "${HTTPS_PORT}:443"   # HTTPS
      - "${ADMIN_PORT}:8080"  # Admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/config:/config
    environment:
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL}
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/traefik/config/users"
      - "traefik.http.routers.traefik.middlewares=traefik-auth,secure-headers@file"

networks:
  traefik-public:
    name: ${DOCKER_NETWORK}
    external: true
