services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traefik-public
    depends_on:
      - bo-chat

  bo-chat:
    # Assuming this is your bo-chat service
    # Replace with your actual bo-chat service configuration
    image: your-bo-chat-image
    container_name: bo-chat
    restart: unless-stopped
    expose:
      - "8081"
    networks:
      - traefik-public

networks:
  traefik-public:
    name: traefik-public
    external: true